In [1]:
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/mohcin/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

# 2.	Outils et environnement de travail 


# 3.	Les bases de la NLP

## 3.1.	Segmentation (Tokenization)

In [2]:
from nltk.tokenize import sent_tokenize, word_tokenize
data="Hello, i am very happy to meet you. I created this course for you. Good by!"
sentences=sent_tokenize(data)
print(sentences)
words=word_tokenize(data)
print(words)

['Hello, i am very happy to meet you.', 'I created this course for you.', 'Good by!']
['Hello', ',', 'i', 'am', 'very', 'happy', 'to', 'meet', 'you', '.', 'I', 'created', 'this', 'course', 'for', 'you', '.', 'Good', 'by', '!']


## 3.2.	Nettoyage(Cleaning) 


In [3]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
data="Hello, i am very happy to meet you. I created this course for you. Good by!"
word_tokens = [word.lower() for word in word_tokenize(data)]
data_clean = [word for word in word_tokens if (not word in set(stopwords.words('english')) and  word.isalpha())]
print(data_clean)

['hello', 'happy', 'meet', 'created', 'course', 'good']


## 3.3.	Racinisation(Stemming)

In [4]:
from nltk.stem import PorterStemmer,SnowballStemmer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
#stemmer=SnowballStemmer('french')
stemmer=PorterStemmer()
data="Le big data  « grosses données » en anglais,les mégadonnées ou les données massives, " \
     "désigne les ressources d’informations dont les caractéristiques en termes de volume," \
     " de vélocité et de variété imposent l’utilisation de technologies et de méthodes analytiques " \
     "particulières pour générer de la valeur, et qui dépassent en général les capacités " \
     "d'une seule et unique machine et nécessitent des traitements parallélisés"
word_tokens = [word.lower() for word in word_tokenize(data)]

for i in range(len(words)):
    words=[stemmer.stem(word) for word in word_tokens if (not word in set(stopwords.words('french')) and  word.isalpha())]
print(words)

['big', 'data', 'gross', 'donné', 'anglai', 'mégadonné', 'donné', 'massiv', 'désign', 'ressourc', 'inform', 'dont', 'caractéristiqu', 'term', 'volum', 'vélocité', 'variété', 'impos', 'utilis', 'technolog', 'méthode', 'analytiqu', 'particulièr', 'générer', 'valeur', 'dépassent', 'général', 'capacité', 'seul', 'uniqu', 'machin', 'nécessit', 'traitement', 'parallélisé']


## 3.4.	Lemmatisation

In [5]:
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

lemmmatizer=WordNetLemmatizer()
data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "
words = word_tokenize(data)
words = [lemmmatizer.lemmatize(word.lower()) for word in words if(not word in set(stopwords.words('english')) and  word.isalpha())]
print(words)

['big', 'data', 'field', 'treat', 'way', 'analyze', 'systematically', 'extract', 'information', 'otherwise', 'deal', 'data', 'set', 'large', 'complex', 'dealt', 'traditional', 'application', 'software', 'data', 'many', 'case', 'row', 'offer', 'greater', 'statistical', 'power', 'data', 'higher', 'complexity', 'attribute', 'column', 'may', 'lead', 'higher', 'false', 'discovery', 'rate']


## 3.5.	POS-Tagging

In [6]:
import nltk
from nltk.tokenize import word_tokenize
data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "
words=word_tokenize(data)
print(nltk.pos_tag(words))

[('Big', 'NNP'), ('data', 'NN'), ('is', 'VBZ'), ('a', 'DT'), ('field', 'NN'), ('that', 'WDT'), ('treats', 'VBZ'), ('ways', 'NNS'), ('to', 'TO'), ('analyze', 'VB'), (',', ','), ('systematically', 'RB'), ('extract', 'JJ'), ('information', 'NN'), ('from', 'IN'), (',', ','), ('or', 'CC'), ('otherwise', 'RB'), ('deal', 'NN'), ('with', 'IN'), ('data', 'NNS'), ('sets', 'NNS'), ('that', 'WDT'), ('are', 'VBP'), ('too', 'RB'), ('large', 'JJ'), ('or', 'CC'), ('complex', 'JJ'), ('to', 'TO'), ('be', 'VB'), ('dealt', 'VBN'), ('with', 'IN'), ('by', 'IN'), ('traditional', 'JJ'), ('data-processing', 'JJ'), ('application', 'NN'), ('software', 'NN'), ('.', '.'), ('Data', 'NNP'), ('with', 'IN'), ('many', 'JJ'), ('cases', 'NNS'), ('(', '('), ('rows', 'NNS'), (')', ')'), ('offer', 'VBP'), ('greater', 'JJR'), ('statistical', 'JJ'), ('power', 'NN'), (',', ','), ('while', 'IN'), ('data', 'NNS'), ('with', 'IN'), ('higher', 'JJR'), ('complexity', 'NN'), ('(', '('), ('more', 'RBR'), ('attributes', 'NNS'), ('or', 

In [7]:
import nltk
from nltk.tokenize import sent_tokenize
data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "


sentences=sent_tokenize(data)

list=[]
for sentence in sentences:
    list.append(word_tokenize(sentence))
    
print(nltk.pos_tag_sents(list))

[[('Big', 'NNP'), ('data', 'NN'), ('is', 'VBZ'), ('a', 'DT'), ('field', 'NN'), ('that', 'WDT'), ('treats', 'VBZ'), ('ways', 'NNS'), ('to', 'TO'), ('analyze', 'VB'), (',', ','), ('systematically', 'RB'), ('extract', 'JJ'), ('information', 'NN'), ('from', 'IN'), (',', ','), ('or', 'CC'), ('otherwise', 'RB'), ('deal', 'NN'), ('with', 'IN'), ('data', 'NNS'), ('sets', 'NNS'), ('that', 'WDT'), ('are', 'VBP'), ('too', 'RB'), ('large', 'JJ'), ('or', 'CC'), ('complex', 'JJ'), ('to', 'TO'), ('be', 'VB'), ('dealt', 'VBN'), ('with', 'IN'), ('by', 'IN'), ('traditional', 'JJ'), ('data-processing', 'JJ'), ('application', 'NN'), ('software', 'NN'), ('.', '.')], [('Data', 'NNP'), ('with', 'IN'), ('many', 'JJ'), ('cases', 'NNS'), ('(', '('), ('rows', 'NNS'), (')', ')'), ('offer', 'VBP'), ('greater', 'JJR'), ('statistical', 'JJ'), ('power', 'NN'), (',', ','), ('while', 'IN'), ('data', 'NNS'), ('with', 'IN'), ('higher', 'JJR'), ('complexity', 'NN'), ('(', '('), ('more', 'RBR'), ('attributes', 'NNS'), ('or

In [8]:
import nltk
nltk.download('brown')
from nltk.corpus import brown
from nltk.tag import UnigramTagger
from nltk.tokenize import word_tokenize

brown_tagged_sents = brown.tagged_sents(categories='news')
size = int(len(brown_tagged_sents) * 0.9)
train_sents = brown_tagged_sents[:size]
test_sents = brown_tagged_sents[size:]
unigram_tagger = nltk.UnigramTagger(train_sents)
print(unigram_tagger.evaluate(test_sents))

data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "
print(unigram_tagger.tag(word_tokenize(data)))

[nltk_data] Downloading package brown to /home/mohcin/nltk_data...
[nltk_data]   Package brown is already up-to-date!


0.8121200039868434
[('Big', 'JJ-TL'), ('data', 'NN'), ('is', 'BEZ'), ('a', 'AT'), ('field', 'NN'), ('that', 'CS'), ('treats', None), ('ways', 'NNS'), ('to', 'TO'), ('analyze', None), (',', ','), ('systematically', None), ('extract', None), ('information', 'NN'), ('from', 'IN'), (',', ','), ('or', 'CC'), ('otherwise', 'RB'), ('deal', 'VB'), ('with', 'IN'), ('data', 'NN'), ('sets', 'VBZ-HL'), ('that', 'CS'), ('are', 'BER'), ('too', 'QL'), ('large', 'JJ'), ('or', 'CC'), ('complex', 'JJ'), ('to', 'TO'), ('be', 'BE'), ('dealt', 'VBD'), ('with', 'IN'), ('by', 'IN'), ('traditional', 'JJ'), ('data-processing', None), ('application', 'NN'), ('software', None), ('.', '.'), ('Data', None), ('with', 'IN'), ('many', 'AP'), ('cases', 'NNS'), ('(', '('), ('rows', None), (')', ')'), ('offer', 'VB'), ('greater', 'JJR'), ('statistical', 'JJ'), ('power', 'NN'), (',', ','), ('while', 'CS'), ('data', 'NN'), ('with', 'IN'), ('higher', 'JJR'), ('complexity', 'NN'), ('(', '('), ('more', 'AP'), ('attributes', 

In [9]:
brown_tagged_sents = brown.tagged_sents(categories='news')
size = int(len(brown_tagged_sents) * 0.9)
train_sents = brown_tagged_sents[:size]
test_sents = brown_tagged_sents[size:]
bigram_tagger = nltk.BigramTagger(train_sents)
print(bigram_tagger.evaluate(test_sents))
data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "
print(bigram_tagger.tag(word_tokenize(data)))

0.10206319146815508
[('Big', None), ('data', None), ('is', None), ('a', None), ('field', None), ('that', None), ('treats', None), ('ways', None), ('to', None), ('analyze', None), (',', None), ('systematically', None), ('extract', None), ('information', None), ('from', None), (',', None), ('or', None), ('otherwise', None), ('deal', None), ('with', None), ('data', None), ('sets', None), ('that', None), ('are', None), ('too', None), ('large', None), ('or', None), ('complex', None), ('to', None), ('be', None), ('dealt', None), ('with', None), ('by', None), ('traditional', None), ('data-processing', None), ('application', None), ('software', None), ('.', None), ('Data', None), ('with', None), ('many', None), ('cases', None), ('(', None), ('rows', None), (')', None), ('offer', None), ('greater', None), ('statistical', None), ('power', None), (',', None), ('while', None), ('data', None), ('with', None), ('higher', None), ('complexity', None), ('(', None), ('more', None), ('attributes', None),

In [10]:
brown_tagged_sents = brown.tagged_sents(categories='news')

size = int(len(brown_tagged_sents) * 0.9)
train_sents = brown_tagged_sents[:size]
test_sents = brown_tagged_sents[size:]
t0 = nltk.DefaultTagger('NN')
t1 = nltk.UnigramTagger(train_sents, backoff=t0)
t2 = nltk.BigramTagger(train_sents, backoff=t1)
print(t2.evaluate(test_sents))
data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "
print(t2.tag(word_tokenize(data)))


0.8452108043456593
[('Big', 'JJ-TL'), ('data', 'NN'), ('is', 'BEZ'), ('a', 'AT'), ('field', 'NN'), ('that', 'CS'), ('treats', 'NN'), ('ways', 'NNS'), ('to', 'TO'), ('analyze', 'NN'), (',', ','), ('systematically', 'NN'), ('extract', 'NN'), ('information', 'NN'), ('from', 'IN'), (',', ','), ('or', 'CC'), ('otherwise', 'RB'), ('deal', 'VB'), ('with', 'IN'), ('data', 'NN'), ('sets', 'VBZ-HL'), ('that', 'CS'), ('are', 'BER'), ('too', 'QL'), ('large', 'JJ'), ('or', 'CC'), ('complex', 'NN'), ('to', 'TO'), ('be', 'BE'), ('dealt', 'VBD'), ('with', 'IN'), ('by', 'IN'), ('traditional', 'JJ'), ('data-processing', 'NN'), ('application', 'NN'), ('software', 'NN'), ('.', '.'), ('Data', 'NN'), ('with', 'IN'), ('many', 'AP'), ('cases', 'NNS'), ('(', '('), ('rows', 'NN'), (')', ')'), ('offer', 'VB'), ('greater', 'JJR'), ('statistical', 'JJ'), ('power', 'NN'), (',', ','), ('while', 'CS'), ('data', 'NN'), ('with', 'IN'), ('higher', 'JJR'), ('complexity', 'NN'), ('(', '('), ('more', 'AP'), ('attributes', 

In [11]:
import nltk
from nltk.tag.stanford import StanfordPOSTagger

data="Le big data  « grosses données » en anglais,les mégadonnées ou les données massives, " \
     "désigne les ressources d’informations dont les caractéristiques en termes de volume," \
     " de vélocité et de variété imposent l’utilisation de technologies et de méthodes analytiques " \
     "particulières pour générer de la valeur, et qui dépassent en général les capacités " \
     "d'une seule et unique machine et nécessitent des traitements parallélisés"
root="/home/mohcin/UM6P/TextMining/TPs/stanford-postagger-full-2020-11-17"
stf = StanfordPOSTagger(root+'/models/french-ud.tagger',root+"/stanford-postagger.jar",encoding='utf8')
tokens = nltk.word_tokenize(data) 
print(stf.tag(tokens))

[('Le', 'DET'), ('big', 'ADJ'), ('data', 'NOUN'), ('«', 'PUNCT'), ('grosses', 'ADJ'), ('données', 'NOUN'), ('»', 'PUNCT'), ('en', 'ADP'), ('anglais', 'NOUN'), (',', 'PUNCT'), ('les', 'DET'), ('mégadonnées', 'NOUN'), ('ou', 'CCONJ'), ('les', 'DET'), ('données', 'NOUN'), ('massives', 'ADJ'), (',', 'PUNCT'), ('désigne', 'VERB'), ('les', 'DET'), ('ressources', 'NOUN'), ('d', 'ADP'), ('’', 'NUM'), ('informations', 'NOUN'), ('dont', 'PRON'), ('les', 'DET'), ('caractéristiques', 'NOUN'), ('en', 'ADP'), ('termes', 'NOUN'), ('de', 'ADP'), ('volume', 'NOUN'), (',', 'PUNCT'), ('de', 'ADP'), ('vélocité', 'NOUN'), ('et', 'CCONJ'), ('de', 'ADP'), ('variété', 'NOUN'), ('imposent', 'VERB'), ('l', 'DET'), ('’', 'PUNCT'), ('utilisation', 'NOUN'), ('de', 'ADP'), ('technologies', 'NOUN'), ('et', 'CCONJ'), ('de', 'ADP'), ('méthodes', 'NOUN'), ('analytiques', 'ADJ'), ('particulières', 'ADJ'), ('pour', 'ADP'), ('générer', 'VERB'), ('de', 'ADP'), ('la', 'DET'), ('valeur', 'NOUN'), (',', 'PUNCT'), ('et', 'CCON

## 3.6.	NER (Named Entity Recognition)

In [12]:
import nltk
from nltk.tokenize import word_tokenize
data="William Henry Gates III (born October 28, 1955) is an American business magnate," \
     " software developer, and philanthropist. He is best known as the co-founder of Microsoft Corporation." \
     "During his career at Microsoft, Gates held the positions of chairman, " \
     "chief executive officer (CEO), president and chief software architect, " \
     "while also being the largest individual shareholder until May 2014. " \
     "He is one of the best-known entrepreneurs and pioneers of the microcomputer " \
     "revolution of the 1970s and 1980s."
words=word_tokenize(data)
print(nltk.ne_chunk(nltk.pos_tag(words)))


(S
  (PERSON William/NNP)
  (PERSON Henry/NNP Gates/NNP III/NNP)
  (/(
  born/JJ
  October/NNP
  28/CD
  ,/,
  1955/CD
  )/)
  is/VBZ
  an/DT
  (GPE American/JJ)
  business/NN
  magnate/NN
  ,/,
  software/NN
  developer/NN
  ,/,
  and/CC
  philanthropist/NN
  ./.
  He/PRP
  is/VBZ
  best/RB
  known/VBN
  as/IN
  the/DT
  co-founder/NN
  of/IN
  (ORGANIZATION Microsoft/NNP)
  Corporation.During/VBG
  his/PRP$
  career/NN
  at/IN
  (ORGANIZATION Microsoft/NNP)
  ,/,
  (PERSON Gates/NNP)
  held/VBD
  the/DT
  positions/NNS
  of/IN
  chairman/NN
  ,/,
  chief/JJ
  executive/NN
  officer/NN
  (/(
  (ORGANIZATION CEO/NNP)
  )/)
  ,/,
  president/NN
  and/CC
  chief/NN
  software/NN
  architect/NN
  ,/,
  while/IN
  also/RB
  being/VBG
  the/DT
  largest/JJS
  individual/JJ
  shareholder/NN
  until/IN
  May/NNP
  2014/CD
  ./.
  He/PRP
  is/VBZ
  one/CD
  of/IN
  the/DT
  best-known/JJ
  entrepreneurs/NNS
  and/CC
  pioneers/NNS
  of/IN
  the/DT
  microcomputer/NN
  revolution/NN
  of/IN
  t

In [13]:
import nltk
nltk.download('words')


[nltk_data] Downloading package words to /home/mohcin/nltk_data...
[nltk_data]   Package words is already up-to-date!


True

## 3.7.	WSD

In [14]:
from nltk.corpus import wordnet
for sens in wordnet.synsets('break'):
    print(">>>",sens.definition())


>>> some abrupt occurrence that interrupts an ongoing activity
>>> an unexpected piece of good luck
>>> (geology) a crack in the earth's crust resulting from the displacement of one side with respect to the other
>>> a personal or social separation (as between opposing factions)
>>> a pause from doing something (as work)
>>> the act of breaking something
>>> a time interval during which there is a temporary cessation of something
>>> breaking of hard tissue such as bone
>>> the occurrence of breaking
>>> an abrupt change in the tone or register of the voice (as at puberty or due to emotion)
>>> the opening shot that scatters the balls in billiards or pool
>>> (tennis) a score consisting of winning a game when your opponent was serving
>>> an act of delaying or interrupting the continuity
>>> a sudden dash
>>> any frame in which a bowler fails to make a strike or spare
>>> an escape from jail
>>> terminate
>>> become separated into pieces or fragments
>>> render inoperable or ineffectiv

In [15]:
from nltk.wsd import lesk
from nltk.tokenize import word_tokenize
context= word_tokenize("I've just finished the first step of the competition. I need a little break to catch my breath")
print(lesk(context, 'break','n').definition())

(geology) a crack in the earth's crust resulting from the displacement of one side with respect to the other


In [16]:
# pip install pywsd
# pip install -U pywsd
#pip install wn==0.0.22
from pywsd.lesk import simple_lesk
sent = 'I went to the bank to deposit my money'
ambiguous = 'bank'
answer = simple_lesk(sent, ambiguous, pos='n')
print (answer)
print (answer.definition())


Warming up PyWSD (takes ~10 secs)... 

Synset('depository_financial_institution.n.01')
a financial institution that accepts deposits and channels the money into lending activities


took 3.0062994956970215 secs.


## 3.8.	Spacy

In [2]:
#python -m spacy download fr_core_news_sm

import spacy

nlp = spacy.load('fr_core_news_sm')

doc = nlp("Le big data  « grosses données » en anglais,les mégadonnées ou les données massives, " \
     "désigne les ressources d’informations dont les caractéristiques en termes de volume," \
     " de vélocité et de variété imposent l’utilisation de technologies et de méthodes analytiques " \
     "particulières pour générer de la valeur, et qui dépassent en général les capacités " \
     "d'une seule et unique machine et nécessitent des traitements parallélisés")

for token in doc:
    print("/token:",token.text, "/lemma:",token.lemma_, token.shape_, token.is_alpha, token.is_stop,"/POS:", token.tag_, "/PARS:", token.head, token.dep_, "/NER:", token.ent_iob_, token.ent_type_)

/token: Le /lemma: le Xx True True /POS: DET /PARS: big det /NER: O 
/token: big /lemma: big xxx True False /POS: NUM /PARS: data nummod /NER: O 
/token: data /lemma: data xxxx True False /POS: ADP /PARS: data ROOT /NER: O 
/token:   /lemma:     False False /POS: SPACE /PARS: data punct /NER: O 
/token: « /lemma: « « False False /POS: NOUN /PARS: « ROOT /NER: O 
/token: grosses /lemma: gros xxxx True False /POS: ADJ /PARS: données amod /NER: O 
/token: données /lemma: donnée xxxx True False /POS: NOUN /PARS: données ROOT /NER: O 
/token: » /lemma: » » False False /POS: PUNCT /PARS: données punct /NER: O 
/token: en /lemma: en xx True True /POS: ADP /PARS: anglais case /NER: O 
/token: anglais /lemma: anglais xxxx True False /POS: NOUN /PARS: données obl:mod /NER: O 
/token: , /lemma: , , False False /POS: PUNCT /PARS: désigne punct /NER: O 
/token: les /lemma: le xxx True True /POS: DET /PARS: mégadonnées det /NER: O 
/token: mégadonnées /lemma: mégadonnée xxxx True False /POS: NOUN /P

# 4.	Model représentatif d’un document

## 4.2. One-hot-vector

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.preprocessing import Binarizer

freq   = CountVectorizer()
corpus = ['This is the first document.','This is the second second document.','And the third one.','Is this the first document?']
corpus=[ sent.lower() for sent in corpus]
corpus = freq.fit_transform(corpus)
print(freq.get_feature_names())
print(corpus.toarray())
onehot = Binarizer()
corpus = onehot.fit_transform(corpus.toarray())
print(corpus)

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]
[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 1 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]


## 4.1.	Bag-of-words

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
corpus = ['This is the first document.','This is the second second document.','And the third one.','Is this the first document?']
corpus=[ sent.lower() for sent in corpus]
X = vectorizer.fit_transform(corpus) #sparsy format

print(X.toarray()) # explicit matrix format
print(vectorizer.get_feature_names() ) #vocabulary as list of string
vectorizer.vocabulary_.get('document') #get column index of a specific term in the vocabulary
vectorizer.transform(['Something completely new.']).toarray()#apply the model to a new document

[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


array([[0, 0, 0, 0, 0, 0, 0, 0, 0]])

## 4.2.	TF-IDF

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = ['This is the first document.','this is the second second Document.','And the third one.','Is this the first document?']
vectorizer = TfidfVectorizer()
X=vectorizer.fit_transform(corpus)
print(X.toarray())
print(vectorizer.get_feature_names() )

#NB: le vecteur tf-idf obtenu sera normalisé pour obtenir des valeurs entre 0 et 1.

[[0.         0.43877674 0.54197657 0.43877674 0.         0.
  0.35872874 0.         0.43877674]
 [0.         0.27230147 0.         0.27230147 0.         0.85322574
  0.22262429 0.         0.27230147]
 [0.55280532 0.         0.         0.         0.55280532 0.
  0.28847675 0.55280532 0.        ]
 [0.         0.43877674 0.54197657 0.43877674 0.         0.
  0.35872874 0.         0.43877674]]
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


# 5.	Cas utilisations : Détection du Plagiarisme 

L’objectif de cet atelier est de détecter le pélagianisme à partir de wikipedia pendant la préparation des réponses à un certain nombre de questions sur des connaissances en informatique. Le dataset utilisé peut-être récupéré à partir du lien suivant :Cliquer <a href="https://ir.shef.ac.uk/cloughie/resources/plagiarism_corpus.html#Download" target="_blank">ICI</a> 

Pour ce faire, nous nous basant sur le calcul des similarités entre les réponses des candidats et les définitions exactes trouvées sur Wikipédia. Deux méthodes de calcul de similarité sont à utiliser, à savoir, la similarité syntaxique et la similarité sémantique.

**Recuperer le dataset
**Réaliser les différentes tâches de prétraitement.

### Importer le dataset

In [21]:
import glob
import os
files=glob.glob('/home/mohcin/UM6P/TextMining/TPs/corpus-20090418/*')
#f_pointers=[open(file,"r",encoding="utf8",errors='ignore') for file in files]
files_names =[os.path.basename(os.path.splitext(file)[0]) for file in sorted(files)]
corpus_wiki = [open(file,"r",encoding="utf8",errors='ignore').read() for file in sorted(files)]
print(files_names)
print('\n')
print(corpus_wiki[:2])

['g0pA_taska', 'g0pA_taskb', 'g0pA_taskc', 'g0pA_taskd', 'g0pA_taske', 'g0pB_taska', 'g0pB_taskb', 'g0pB_taskc', 'g0pB_taskd', 'g0pB_taske', 'g0pC_taska', 'g0pC_taskb', 'g0pC_taskc', 'g0pC_taskd', 'g0pC_taske', 'g0pD_taska', 'g0pD_taskb', 'g0pD_taskc', 'g0pD_taskd', 'g0pD_taske', 'g0pE_taska', 'g0pE_taskb', 'g0pE_taskc', 'g0pE_taskd', 'g0pE_taske', 'g1pA_taska', 'g1pA_taskb', 'g1pA_taskc', 'g1pA_taskd', 'g1pA_taske', 'g1pB_taska', 'g1pB_taskb', 'g1pB_taskc', 'g1pB_taskd', 'g1pB_taske', 'g1pD_taska', 'g1pD_taskb', 'g1pD_taskc', 'g1pD_taskd', 'g1pD_taske', 'g2pA_taska', 'g2pA_taskb', 'g2pA_taskc', 'g2pA_taskd', 'g2pA_taske', 'g2pB_taska', 'g2pB_taskb', 'g2pB_taskc', 'g2pB_taskd', 'g2pB_taske', 'g2pC_taska', 'g2pC_taskb', 'g2pC_taskc', 'g2pC_taskd', 'g2pC_taske', 'g2pE_taska', 'g2pE_taskb', 'g2pE_taskc', 'g2pE_taskd', 'g2pE_taske', 'g3pA_taska', 'g3pA_taskb', 'g3pA_taskc', 'g3pA_taskd', 'g3pA_taske', 'g3pB_taska', 'g3pB_taskb', 'g3pB_taskc', 'g3pB_taskd', 'g3pB_taske', 'g3pC_taska', 'g3pC

<b>Pour réaliser les tâches de prétraitement on utilise la library spacy</b>

In [22]:
import spacy
nlp = spacy.load('en_core_web_sm')
doc = [nlp(doc) for doc in corpus_wiki] # appliquer le modéle nlp sur tous les docs du corpus

### Tokenization

In [23]:
docs_tokens = []
for d in doc:
    tokens = [token.text for token in d]
    docs_tokens.append(tokens)
print(docs_tokens)

[['Inheritance', 'is', 'a', 'basic', 'concept', 'of', 'Object', '-', 'Oriented', 'Programming', 'where', '\n', 'the', 'basic', 'idea', 'is', 'to', 'create', 'new', 'classes', 'that', 'add', 'extra', 'detail', 'to', '\n', 'existing', 'classes', '.', 'This', 'is', 'done', 'by', 'allowing', 'the', 'new', 'classes', 'to', 'reuse', '\n', 'the', 'methods', 'and', 'variables', 'of', 'the', 'existing', 'classes', 'and', 'new', 'methods', 'and', '\n', 'classes', 'are', 'added', 'to', 'specialise', 'the', 'new', 'class', '.', 'Inheritance', 'models', 'the', '\n', '“', 'is', '-', 'kind', '-', 'of', '”', 'relationship', 'between', 'entities', '(', 'or', 'objects', ')', ',', 'for', 'example', ',', '\n', 'postgraduates', 'and', 'undergraduates', 'are', 'both', 'kinds', 'of', 'student', '.', 'This', 'kind', '\n', 'of', 'relationship', 'can', 'be', 'visualised', 'as', 'a', 'tree', 'structure', ',', 'where', '‘', 'student', '’', '\n', 'would', 'be', 'the', 'more', 'general', 'root', 'node', 'and', 'bot

### Nettoyage(Cleaning) 

In [24]:
from spacy.lang.en.stop_words import STOP_WORDS

def clean_data(doc):
    lower_data = [word.lower() for word in doc]
    clean_data = [word for word in lower_data if (not word in STOP_WORDS and  word.isalpha())]
    return (clean_data)


clean_docs = []
for tokens in docs_tokens:
    clean_docs.append(clean_data(tokens))
print(clean_docs)

[['inheritance', 'basic', 'concept', 'object', 'oriented', 'programming', 'basic', 'idea', 'create', 'new', 'classes', 'add', 'extra', 'detail', 'existing', 'classes', 'allowing', 'new', 'classes', 'reuse', 'methods', 'variables', 'existing', 'classes', 'new', 'methods', 'classes', 'added', 'specialise', 'new', 'class', 'inheritance', 'models', 'kind', 'relationship', 'entities', 'objects', 'example', 'postgraduates', 'undergraduates', 'kinds', 'student', 'kind', 'relationship', 'visualised', 'tree', 'structure', 'student', 'general', 'root', 'node', 'postgraduate', 'undergraduate', 'specialised', 'extensions', 'student', 'node', 'child', 'nodes', 'relationship', 'student', 'known', 'superclass', 'parent', 'class', 'postgraduate', 'known', 'subclass', 'child', 'class', 'postgraduate', 'class', 'extends', 'student', 'class', 'inheritance', 'occur', 'layers', 'visualised', 'display', 'larger', 'tree', 'structure', 'example', 'extend', 'postgraduate', 'node', 'adding', 'extra', 'extended'

### Lemmatisation

In [25]:
docs_lemmas = []
for d in doc:
    lemmas = [token.lemma_ for token in d] # récupérer les lemmas de chaque doc 
    docs_lemmas.append(clean_data(lemmas)) # nettoyer les lemmas
print(docs_lemmas)

[['inheritance', 'basic', 'concept', 'object', 'orient', 'programming', 'basic', 'idea', 'create', 'new', 'class', 'add', 'extra', 'detail', 'exist', 'class', 'allow', 'new', 'class', 'reuse', 'method', 'variable', 'exist', 'class', 'new', 'method', 'class', 'add', 'specialise', 'new', 'class', 'inheritance', 'model', 'kind', 'relationship', 'entity', 'object', 'example', 'postgraduate', 'undergraduate', 'kind', 'student', 'kind', 'relationship', 'visualise', 'tree', 'structure', 'student', 'general', 'root', 'node', 'postgraduate', 'undergraduate', 'specialised', 'extension', 'student', 'node', 'child', 'node', 'relationship', 'student', 'know', 'superclass', 'parent', 'class', 'postgraduate', 'know', 'subclass', 'child', 'class', 'postgraduate', 'class', 'extend', 'student', 'class', 'inheritance', 'occur', 'layer', 'visualise', 'display', 'large', 'tree', 'structure', 'example', 'far', 'extend', 'postgraduate', 'node', 'add', 'extra', 'extended', 'class', 'msc', 'student', 'phd', 's

### POS-Tagging

In [26]:
docs_tags = []
for d in doc:
    # récupérer le tag de chaque lemma
    tags = [(token.lemma_,token.tag_) for token in d]
    # nettoyer le tuple (lemma,tag)
    lower_data = [(word[0].lower(),word[1]) for word in tags]
    clean_data = [(word[0],word[1]) for word in lower_data if (not word[0] in STOP_WORDS and  word[0].isalpha())]
    docs_tags.append(clean_data)
print(docs_tags)

[[('inheritance', 'NN'), ('basic', 'JJ'), ('concept', 'NN'), ('object', 'NNP'), ('orient', 'VBN'), ('programming', 'NN'), ('basic', 'JJ'), ('idea', 'NN'), ('create', 'VB'), ('new', 'JJ'), ('class', 'NNS'), ('add', 'VBP'), ('extra', 'JJ'), ('detail', 'NN'), ('exist', 'VBG'), ('class', 'NNS'), ('allow', 'VBG'), ('new', 'JJ'), ('class', 'NNS'), ('reuse', 'VB'), ('method', 'NNS'), ('variable', 'NNS'), ('exist', 'VBG'), ('class', 'NNS'), ('new', 'JJ'), ('method', 'NNS'), ('class', 'NNS'), ('add', 'VBN'), ('specialise', 'VB'), ('new', 'JJ'), ('class', 'NN'), ('inheritance', 'NN'), ('model', 'NNS'), ('kind', 'NN'), ('relationship', 'NN'), ('entity', 'NNS'), ('object', 'NNS'), ('example', 'NN'), ('postgraduate', 'NNS'), ('undergraduate', 'NNS'), ('kind', 'NNS'), ('student', 'NN'), ('kind', 'NN'), ('relationship', 'NN'), ('visualise', 'VBN'), ('tree', 'NN'), ('structure', 'NN'), ('student', 'NN'), ('general', 'JJ'), ('root', 'NN'), ('node', 'NN'), ('postgraduate', 'VB'), ('undergraduate', 'NN')

### NER (Named Entity Recognition)

In [27]:
NER = []
for d in doc:
    ner = [(ent.text,ent.label_) for ent in d.ents]
    NER.append(ner)
print(NER)

[[('Object-Oriented Programming', 'ORG'), ('two', 'CARDINAL'), ('PhD Student’', 'WORK_OF_ART'), ('PhD Student’', 'WORK_OF_ART')], [('PageRank', 'ORG'), ('0-10', 'CARDINAL'), ('PageRank', 'ORG'), ('PageRank', 'ORG'), ('PageRank', 'ORG'), ('PageRank', 'ORG'), ('PageRank', 'ORG'), ('PR(E', 'GPE'), ('PageRank', 'ORG'), ('Jon Kleinberg', 'PERSON'), ('IBM', 'ORG'), ('TrustRank', 'ORG')], [('first', 'ORDINAL'), ('non-zero', 'CARDINAL'), ('One', 'CARDINAL'), ('Firstly', 'ORDINAL'), ('Secondly', 'ORDINAL'), ('Thirdly', 'ORDINAL')], [('Bayes', 'ORG'), ('Rev Thomas Bayes', 'PERSON'), ('two', 'CARDINAL'), ('Bayes', 'ORG'), ('Bayes', 'ORG'), ('Bayes', 'ORG'), ('forty percent', 'PERCENT'), ('Bayesians', 'NORP'), ('Bayes’', 'ORG'), ('Frequentist', 'NORP'), ('Bayesian', 'NORP'), ('Bayesians', 'NORP')], [('Dynamic Programming', 'PERSON'), ('Dynamic Programming', 'PERSON'), ('one', 'CARDINAL'), ('four', 'CARDINAL'), ('Dynamic Programming', 'WORK_OF_ART'), ('1', 'CARDINAL'), ('2', 'CARDINAL'), ('3', 'CAR

In [28]:
# visualizer
from spacy import displacy

for d in doc:
    displacy.render(d, style="ent", jupyter=True)

/home/mohcin/anaconda3/lib/python3.7/site-packages/spacy/displacy/__init__.py:189: UserWarning: [W006] No entities to visualize found in Doc object. If this is surprising to you, make sure the Doc was processed using a model that supports named entity recognition, and check the `doc.ents` property manually if necessary.
  warnings.warn(Warnings.W006)


## 5.1 similarité syntaxique 

Pour la similarité syntaxique entre des vecteurs, plusieurs distances sont possibles à savoir : distance, euclidienne, Cosine Jaccard, Levenshtein, Hamming…

l'exemple ci-dessous permet de calculer la similarité. semantique entre les documents en se basant sur une representation vectorielle en TFIDF avec la distance euclidienne. 

In [177]:
from sklearn.metrics.pairwise import cosine_distances,euclidean_distances
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import Binarizer
import time

    
def tfidf_simil(corpus,index_of_doc):
   
    #tfidf_matrix = tfidf_matrix.toarray()
    #compute similarity for first sentence with rest of the sentences
    return (cosine_distances(corpus[index_of_doc:index_of_doc+1],corpus))

def ohv_simil(corpus,index_of_doc):
    vectorizer  = CountVectorizer()
    corpus=[ sent.lower() for sent in corpus]
    corpus = vectorizer.fit_transform(corpus)

    onehot = Binarizer()
    ohv = onehot.fit_transform(corpus.toarray())

    return (cosine_distances(ohv[index_of_doc:index_of_doc+1],ohv))

def bow_simil(corpus,index_of_doc):
    vectorizer = CountVectorizer(lowercase=True)
    corpus=[ sent.lower() for sent in corpus]
    X = vectorizer.fit_transform(corpus) #sparsy format
    bow = X.toarray()
    
    return (cosine_distances(bow[index_of_doc:index_of_doc+1],bow))


**Realiser la même chose en se basant sur les representations OHV et BOW?
**Comparer les performances des trois methodes en terme de temps d'execution et precision.  

In [173]:
my_corpus = ['This is the first document.','This is the second second document.','And the third one.','Is this the first document?']

tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(my_corpus)

start_time = time.time()
print(tfidf_simil(tfidf_matrix,0))
end_time = time.time()
print('tfidf executed in',end_time-start_time,'s')

[[0.         0.56169962 0.8965151  0.        ]]
tfidf executed in 0.0024864673614501953 s


In [168]:
start_time = time.time()
print(ohv_simil(my_corpus,0))
end_time = time.time()
print('tfidf executed in',end_time-start_time,'s')

[[1.        0.8       0.2236068 1.       ]]
tfidf executed in 0.0028257369995117188 s


In [169]:
start_time = time.time()
print(bow_simil(my_corpus,0))
end_time = time.time()
print('tfidf executed in',end_time-start_time,'s')

[[1.         0.63245553 0.2236068  1.        ]]
tfidf executed in 0.0031936168670654297 s


<b> Interprétation : TFIDF est plus précis mais BOW est plus rapide </b>

Il existe d'autre methodes(orientées caractères) pour le calcule de la similarité syntaxique entre des documents courts (des phrases):

* Longest Common Sequence (LCS)
* Set features
* Word Order Similarity
* n-gram sentences 
* Jaro-Winkler
* ...

Cliquer <a href="http://www.iaeme.com/MasterAdmin/Journal_uploads/IJCET/VOLUME_9_ISSUE_5/IJCET_09_05_001.pdf" target="_blank">ICI</a> pour plus de details



## Test

**Calculer les similarités syntaxiques entre les réponses des étudiants et les définitions trouvées sur wikipedia.


In [164]:
# séparer les tasks dans différents corpus
task_a = corpus_wiki[slice(0,100,5)]
task_b = corpus_wiki[slice(1,100,5)]
task_c = corpus_wiki[slice(2,100,5)]
task_d = corpus_wiki[slice(3,100,5)]
task_e = corpus_wiki[slice(4,100,5)]

task_a_names = files_names[slice(0,100,5)]
task_b_names = files_names[slice(1,100,5)]
task_c_names = files_names[slice(2,100,5)]
task_d_names = files_names[slice(3,100,5)]
task_e_names = files_names[slice(4,100,5)]

In [171]:
import pandas as pd

tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus_wiki)

task_a = tfidf_matrix[slice(0,100,5)]
task_b = tfidf_matrix[slice(1,100,5)]
task_c = tfidf_matrix[slice(2,100,5)]
task_d = tfidf_matrix[slice(3,100,5)]
task_e = tfidf_matrix[slice(4,100,5)]

task_a_names = files_names[slice(0,100,5)]
task_b_names = files_names[slice(1,100,5)]
task_c_names = files_names[slice(2,100,5)]
task_d_names = files_names[slice(3,100,5)]
task_e_names = files_names[slice(4,100,5)]

print("similarité task A")
df_taskA = pd.DataFrame(tfidf_simil(task_a,19)[0][:19],task_a_names[:19],task_a_names[19:20])
print(df_taskA)
print("la réponse la plus similaire est : ",df_taskA.orig_taska.idxmax())

print("\nsimilarité task B")
df_taskB = pd.DataFrame(tfidf_simil(task_b,19)[0][:19],task_b_names[:19],task_b_names[19:20])
print(df_taskB)
print("la réponse la plus similaire est : ",df_taskB.orig_taskb.idxmax())


print("\nsimilarité task C")
df_taskC = pd.DataFrame(tfidf_simil(task_c,19)[0][:19],task_c_names[:19],task_c_names[19:20])
print(df_taskC)
print("la réponse la plus similaire est : ",df_taskC.orig_taskc.idxmax())

print("\nsimilarité task D")
df_taskD = pd.DataFrame(tfidf_simil(task_d,19)[0][:19],task_d_names[:19],task_d_names[19:20])
print(df_taskD)
print("la réponse la plus similaire est : ",df_taskD.orig_taskd.idxmax())

print("\nsimilarité task E")
df_taskE = pd.DataFrame(tfidf_simil(task_e,19)[0][:19],task_e_names[:19],task_e_names[19:20])
print(df_taskE)
print("la réponse la plus similaire est : ",df_taskE.orig_taske.idxmax())

similarité task A
            orig_taska
g0pA_taska    0.743859
g0pB_taska    0.847466
g0pC_taska    0.469422
g0pD_taska    0.162572
g0pE_taska    0.031334
g1pA_taska    0.610974
g1pB_taska    0.737584
g1pD_taska    0.344519
g2pA_taska    0.808609
g2pB_taska    0.784711
g2pC_taska    0.303275
g2pE_taska    0.136716
g3pA_taska    0.633644
g3pB_taska    0.700366
g3pC_taska    0.238867
g4pB_taska    0.773817
g4pC_taska    0.015646
g4pD_taska    0.352191
g4pE_taska    0.674867
la réponse la plus similaire est :  g0pB_taska

similarité task B
            orig_taskb
g0pA_taskb    0.212704
g0pB_taskb    0.473885
g0pC_taskb    0.595879
g0pD_taskb    0.511428
g0pE_taskb    0.514099
g1pA_taskb    0.450773
g1pB_taskb    0.509826
g1pD_taskb    0.467618
g2pA_taskb    0.308045
g2pB_taskb    0.499486
g2pC_taskb    0.421420
g2pE_taskb    0.374237
g3pA_taskb    0.238449
g3pB_taskb    0.470001
g3pC_taskb    0.537194
g4pB_taskb    0.639007
g4pC_taskb    0.497598
g4pD_taskb    0.550576
g4pE_taskb    0.183

## 5.2 similarité semantique : Approche lexicale

In [35]:
from nltk.corpus import wordnet as wn 
computer_synsets = wn.synsets("computer") 
print("Computer sens in wordNet:")
i=0;
for sense in computer_synsets: 
    print(" \t Sens :", i)
    print(" \t\t Sens definition: "+sense.definition())
    lemmas = [l.name() for l in sense.lemmas()]
    print("\t\t Lemmas for sense :" +str(lemmas))
    i=i+1

Computer sens in wordNet:
 	 Sens : 0
 		 Sens definition: a machine for performing calculations automatically
		 Lemmas for sense :['computer', 'computing_machine', 'computing_device', 'data_processor', 'electronic_computer', 'information_processing_system']
 	 Sens : 1
 		 Sens definition: an expert at calculation (or at operating calculating machines)
		 Lemmas for sense :['calculator', 'reckoner', 'figurer', 'estimator', 'computer']


In [122]:
from nltk.corpus import wordnet as wn 
import pandas as pd
import numpy as np
computer_synsets = wn.synsets("computer",'n')
device_synsets = wn.synsets("device") 
lch=[]
wup=[]

for s1 in computer_synsets:
    for s2 in device_synsets:
        lch.append(s1.lch_similarity(s2))
        wup.append(s1.wup_similarity(s2))

pd.DataFrame([lch,wup],["lch","wup"])


0         1         2         3         4         5         6  \
lch  2.538974  1.072637  0.693147  1.558145  1.440362  1.440362  1.335001   
wup  0.875000  0.142857  0.100000  0.588235  0.555556  0.500000  0.181818   

            7         8         9  
lch  0.864997  1.335001  1.239691  
wup  0.117647  0.470588  0.444444

In [54]:
doc1='Computer science is the study of computers and computing concepts. It includes both hardware and software, as well as networking and the Internet'
context= word_tokenize(doc1)
sens=lesk(context, 'Computer')
print(sens)

Synset('computer.n.01')


In [49]:
from nltk.wsd import lesk
from nltk.tokenize import word_tokenize
def WSD(word, context):
    sens=lesk(context, word)
    return sens

doc1='Computer science is the study of computers and computing concepts. It includes both hardware and software, as well as networking and the Internet'
doc2='Computer science is the science that deals with the theory and methods of processing information in digital computers, the design of computer hardware and software, and the applications of computers.'


print(WSD("Computer", doc1).definition())
print(WSD("Computer", doc2).definition())

a machine for performing calculations automatically
a machine for performing calculations automatically


**Defnir la fonction SemanticDistanceDocs(doc1,doc2) qui permet de calculer la distance semantique totale entre deux documents texte

In [134]:
from nltk.corpus import wordnet as wn
from nltk.tokenize import word_tokenize

# définir une fonction pour calculer le sens d'un mot selon le contexte
def word_sem(word,context):
    sens=lesk(context, word)
    return sens

# fonction pour calculer la similarité entre deux docs
def SemanticDistanceDocs(doc1,doc2):
    
    # tokeniz the two docs
    contextDoc1 = word_tokenize(doc1)
    contextDoc2 = word_tokenize(doc2)
    
    # retourne les sens de tous les mots
    sensDoc1=[word_sem(word,contextDoc1) for word in contextDoc1]
    sensDoc2=[word_sem(word,contextDoc2) for word in contextDoc2]
    
    # Filtrer les None
    sensDoc1 = [ss for ss in sensDoc1 if ss is not None]
    sensDoc2 = [ss for ss in sensDoc2 if ss is not None]
    
    sim = []
    
    ## pour chaque sens du doc1 on calcule la similarité à l'aide de la fonction path_similarity
    for s1 in sensDoc1:
        best_score = []
        for s2 in sensDoc2:
            score = s1.path_similarity(s2)
            
            if score is not None:
                best_score.append(score)

        if(best_score):
            sim.append(max(best_score)) # on stocke le similarité du deux mot les plus similaire
            
        
    return sum(sim)/len(sim) # le simalirité entre les deux docs est la moyenne de tous les similarité


# la fonction SemanticDistanceDocs retourne deux score différent pour doc1,doc2 et doc2,doc1
# on va crée une fonction retourne une similarité symétrique
def SymSemanticDistanceDocs(doc1,doc2):
    return (SemanticDistanceDocs(doc1,doc2)+SemanticDistanceDocs(doc2,doc1))/2

In [135]:
# test
doc1='Computer science is the study of computers and computing concepts. It includes both hardware and software, as well as networking and the Internet'
doc2='Computer science is the science that deals with the theory and methods of processing information in digital computers, the design of computer hardware and software, and the applications of computers.'

SymSemanticDistanceDocs(doc1,doc2)

0.4241939484126984

## Test

**Calculer les similarités syntaxiques entre les réponses des étudiants et les définitions trouvées sur wikipedia.

In [140]:
# fonction pour calculer la similarité du corpus wiki
def sim_wiki(corpus,index_of_doc):
    sim_list = []
    for doc in corpus:
        sim_list.append(SymSemanticDistanceDocs(doc,corpus[index_of_doc]))
    return sim_list

In [147]:
sim_taska = sim_wiki(task_a,19)[:19]
sim_taskb = sim_wiki(task_b,19)[:19]
sim_taskc = sim_wiki(task_c,19)[:19]
sim_taskd = sim_wiki(task_d,19)[:19]
sim_taske = sim_wiki(task_e,19)[:19]

In [148]:
print("similarité task A")
df_taskA = pd.DataFrame(sim_taska,task_a_names[:19],task_a_names[19:20])
print(df_taskA)
print("la réponse la plus similaire est : ",df_taskA.orig_taska.idxmax())

print("\nsimilarité task B")
df_taskB = pd.DataFrame(sim_taskb,task_b_names[:19],task_b_names[19:20])
print(df_taskB)
print("la réponse la plus similaire est : ",df_taskB.orig_taskb.idxmax())


print("\nsimilarité task C")
df_taskC = pd.DataFrame(sim_taskc,task_c_names[:19],task_c_names[19:20])
print(df_taskC)
print("la réponse la plus similaire est : ",df_taskC.orig_taskc.idxmax())

print("\nsimilarité task D")
df_taskD = pd.DataFrame(sim_taskd,task_d_names[:19],task_d_names[19:20])
print(df_taskD)
print("la réponse la plus similaire est : ",df_taskD.orig_taskd.idxmax())

print("\nsimilarité task E")
df_taskE = pd.DataFrame(sim_taske,task_e_names[:19],task_e_names[19:20])
print(df_taskE)
print("la réponse la plus similaire est : ",df_taskE.orig_taske.idxmax())

similarité task A
            orig_taska
g0pA_taska    0.391858
g0pB_taska    0.535419
g0pC_taska    0.688628
g0pD_taska    0.862083
g0pE_taska    0.976004
g1pA_taska    0.578637
g1pB_taska    0.451541
g1pD_taska    0.767558
g2pA_taska    0.540315
g2pB_taska    0.592242
g2pC_taska    0.802616
g2pE_taska    0.936574
g3pA_taska    0.616832
g3pB_taska    0.618146
g3pC_taska    0.840922
g4pB_taska    0.602816
g4pC_taska    0.957544
g4pD_taska    0.752228
g4pE_taska    0.646216
la réponse la plus similaire est :  g0pE_taska

similarité task B
            orig_taskb
g0pA_taskb    0.748905
g0pB_taskb    0.718003
g0pC_taskb    0.544037
g0pD_taskb    0.656223
g0pE_taskb    0.577741
g1pA_taskb    0.592370
g1pB_taskb    0.603716
g1pD_taskb    0.651441
g2pA_taskb    0.638013
g2pB_taskb    0.606509
g2pC_taskb    0.557022
g2pE_taskb    0.700735
g3pA_taskb    0.710645
g3pB_taskb    0.660216
g3pC_taskb    0.568499
g4pB_taskb    0.565016
g4pC_taskb    0.586125
g4pD_taskb    0.534098
g4pE_taskb    0.771